const data = [
  {
    id: 1,
    title: "Atlas of the Heart",
    author: "Brené Brown",
    genre: "Fiction",
  },
  {
    id: 2,
    title: "The Subtle Art of Not Giving",
    author: "Mark Manson",
    genre: "Novel",
  },
  {
    id: 3,
    title: "The Midnight Library",
    author: "Matt Haig",
    genre: "Narrative",
  },
  {
    id: 4,
    title: "The Body Keeps the Score",
    author: "Bessel van der Kolk",
    genre: "Novel",
  },
  {
    id: 5,
    title: "The Four Agreements",
    author: "Matt Haig",
    genre: "Fiction",
  },
  {
    id: 6,
    title: "Ugly Love",
    author: "Bessel van der Kolk",
    genre: "Narrative",
  },
  {
    id: 7,
    title: "It Ends with Us",
    author: "Brené Brown",
    genre: "Fiction",
  },
  {
    id: 8,
    title: "Atomic Habits",
    author: "Bessel van der Kolk",
    genre: "Novel",
  },
  {
    id: 9,
    title: "It Ends with love",
    author: "Brené Brown",
    genre: "Fiction",
  },
  {
    id: 17,
    title: "Atlas of the Heart 2",
    author: "Brené Brown",
    genre: "Fiction",
  },
  {
    id: 10,
    title: "The Subtle Art of Not Giving 2",
    author: "Mark Manson",
    genre: "Novel",
  },
  {
    id: 11,
    title: "The Midnight Library 2",
    author: "Matt Haig",
    genre: "Narrative",
  },
  {
    id: 12,
    title: "The Body Keeps the Score 2",
    author: "Bessel van der Kolk",
    genre: "Novel",
  },
  {
    id: 13,
    title: "The Four Agreements 2",
    author: "Matt Haig",
    genre: "Fiction",
  },
  {
    id: 14,
    title: "Ugly Love 2",
    author: "Bessel van der Kolk",
    genre: "Narrative",
  },
  {
    id: 15,
    title: "It Ends with Us 2",
    author: "Brené Brown",
    genre: "Fiction",
  },
  {
    id: 16,
    title: "Atomic Habits 2",
    author: "Bessel van der Kolk",
    genre: "Novel",
  },
];
export default data;
